name: Run Tests

on:
  schedule:
    - cron: "0 10 * * 1"
  push:
    branches:
      - master
  pull_request:
    branches:
    - master

jobs:
  create_project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Generate project
      run: npx create-react-app tmp --template file:.
    - name: Run tests on default project
      run: |
        cd tmp
        CI=true yarn test
    - name: Use plop
      run: |
        cd tmp
        yarn plop component test ./src/shared/components
        yarn plop module test
        yarn plop hook test ./src/shared/components
    - name: Run tests with snapshots update
      run: |
        cd tmp
        CI=true yarn test -u
    - name: Build
      run: |
        cd tmp
        yarn build