name: Run Tests

on:
  schedule:
    - cron: "0 10 * * 1"
  push:
    branches:
      - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Generate project
      run: npx create-react-app tmp --template file:.
    - name: Run tests
      run: |
        cd tmp
        CI=true yarn test
